const TG=window.Telegram?.WebApp; TG?.ready(); TG?.expand();
const gifts=[
{name:'Jelly Bunny',id:'jellybunny-4025',value:18,img:'https://nft.fragment.com/gift/jellybunny-4025.medium.jpg'},
{name:'Homemade Cake',id:'homemadecake-28124',value:14,img:'https://nft.fragment.com/gift/homemadecake-28124.medium.jpg'},
{name:'Jelly Bunny',id:'jellybunny-2608',value:22,img:'https://nft.fragment.com/gift/jellybunny-2608.medium.jpg'},
{name:'Homemade Cake',id:'homemadecake-60369',value:31,img:'https://nft.fragment.com/gift/homemadecake-60369.medium.jpg'},
{name:'Jelly Bunny',id:'jellybunny-41980',value:48,img:'https://nft.fragment.com/gift/jellybunny-41980.medium.jpg'}
];
let state=JSON.parse(localStorage.getItem('giftup')||'null')||{points:1000,games:0,wins:0,history:[],inventory:[...gifts]};
let peer=null,conn=null;
const $=s=>document.querySelector(s),fmt=n=>Math.round(n).toLocaleString('ru-RU');
function save(){localStorage.setItem('giftup',JSON.stringify(state));render()}
function render(){['balance','balance2'].forEach(id=>$('#'+id).textContent=fmt(state.points));$('#gamesCount').textContent=state.games;$('#winsCount').textContent=state.wins;$('#winrate').textContent=state.games?Math.round(state.wins/state.games*100)+'%':'0%';$('#history').innerHTML=state.history.slice(0,12).map(x=>`<div class="row card"><div class="grow"><b>${x.name}</b><div class="muted" style="font-size:11px">${x.time}</div></div><span class="${x.win?'success':'danger'}">${x.win?'+':'-'}${fmt(x.points)} pts</span></div>`).join('')||'<div class="muted">Пока нет сыгранных матчей.</div>';$('#inventory').innerHTML=state.inventory.map(g=>giftHTML(g)).join('')}
function giftHTML(g){return `<div class="card gift"><img src="${g.img}" loading="lazy"><b>${g.name}</b><span>${g.value} pts · #${g.id.split('-').pop()}</span></div>`}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('#'+page).classList.add('active');document.querySelectorAll('.nav button[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page))}
document.querySelectorAll('.nav button[data-page]').forEach(b=>b.onclick=()=>nav(b.dataset.page));
function profile(){const u=TG?.initDataUnsafe?.user;if(u){$('#profileName').textContent=[u.first_name,u.last_name].filter(Boolean).join(' ');$('#profileUser').textContent=u.username?'@'+u.username:'без username';$('#profileId').textContent='ID: '+u.id;if(u.photo_url)$('#profileAvatar').src=u.photo_url}else $('#profileAvatar').src='https://api.dicebear.com/9.x/initials/svg?seed=Gift%20Player&backgroundColor=1675df'}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
function record(name,win,points){state.games++;if(win)state.wins++;state.history.unshift({name,win,points,time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})});save()}
function openGame(type){({battle:battleSetup,coinflip:coinflip,mines:mines,upgrade:upgrade,contract:contract,duel:duel}[type]||battleSetup)()}
function battleSetup(){openModal('Case Battle',`<div class="room"><p class="muted">Все участники открывают одинаковые виртуальные кейсы. Побеждает игрок с наибольшей суммой очков за все раунды. Здесь используются только игровые очки, без денежных ставок и вывода.</p><div class="card" style="padding:14px"><b>Gift Rush · 5 раундов</b><div class="gifts" style="margin-top:10px">${gifts.slice(0,4).map(g=>giftHTML(g)).join('')}</div></div><button class="primary" onclick="startBattle()">Начать матч</button> <button class="secondary" onclick="openRooms()">Играть с другом</button></div>`)}
function startBattle(){let score=0,round=0;openModal('Gift Rush — раунд 1',`<div class="gameStage"><div class="badge" id="roundBadge">ROUND 1 / 5</div><div class="caseSpin" id="caseSpin">${gifts.concat(gifts,gifts).map(g=>`<div class="caseItem"><img src="${g.img}"><div>${g.name}</div></div>`).join('')}</div><button class="primary" id="spinBtn" onclick="spinBattle()">Открыть кейс</button><div id="battleResult"></div></div>`);window.battle={score,round}}
function spinBattle(){const b=window.battle;if(!b)return;const btn=$('#spinBtn');btn.disabled=true;$('#caseSpin').style.transition='transform 1.9s cubic-bezier(.12,.7,.12,1)';$('#caseSpin').style.transform=`translateX(-${180+Math.floor(Math.random()*700)}px)`;setTimeout(()=>{const g=gifts[Math.floor(Math.random()*gifts.length)];b.score+=g.value;b.round++;$('#battleResult').innerHTML=`<div class="result success">${g.name} · +${g.value} pts</div><div class="muted">Твой счёт: ${b.score}</div>`;if(b.round<5){$('#roundBadge').textContent=`ROUND ${b.round+1} / 5`;btn.disabled=false;$('#caseSpin').style.transform='translateX(0)'}else{const win=b.score>=90;record('Case Battle',win,b.score);$('#battleResult').innerHTML+=`<div class="result ${win?'success':'danger'}">${win?'ПОБЕДА':'РАУНД ЗА СОПЕРНИКОМ'}</div><button class="secondary" onclick="closeModal()">Закрыть</button> `}},2100)}
function coinflip(){openModal('Coinflip',`<div class="gameStage"><p class="muted">Соревновательная мини-игра: выбери сторону и сравни результат с виртуальным соперником. Это только игровой счёт.</p><div class="actions" style="justify-content:center"><button class="primary" onclick="flip('Орёл')">Орёл</button><button class="secondary" onclick="flip('Решка')">Решка</button></div><div id="flipResult" class="result"></div></div>`)}
function flip(side){const result=Math.random()<.5?'Орёл':'Решка',win=side===result;const pts=win?25:10;if(win)state.points+=pts;record('Coinflip',win,pts);$('#flipResult').innerHTML=`Выпало: <b>${result}</b><div class="${win?'success':'danger'}">${win?'+25':'-10'} pts</div>`;if(!win)state.points=Math.max(0,state.points-10);save()}
function mines(){openModal('Mines',`<div class="gameStage"><p class="muted">Открывай клетки и набирай очки. Мины сбрасывают текущий раунд, но не затрагивают твой инвентарь.</p><div>Множитель: <b id="mult">1.00x</b></div><div class="mineGrid" id="mineGrid">${Array.from({length:25},(_,i)=>`<button class="mine" onclick="minePick(${i})"></button>`).join('')}</div><button class="secondary" onclick="mineCashout()">Зафиксировать счёт</button><div id="mineMsg" class="muted" style="margin-top:10px">Открой клетку</div></div>`);window.mineGame={mine:Math.floor(Math.random()*25),opened:[],mult:1}}
function minePick(i){const m=window.mineGame;if(m.opened.includes(i))return;m.opened.push(i);const el=document.querySelectorAll('.mine')[i];el.classList.add('revealed');if(i===m.mine){el.textContent='×';$('#mineMsg').innerHTML='<span class="danger">Мина! Раунд завершён.</span>';record('Mines',false,20);return}m.mult*=1.18;el.textContent='◆';$('#mult').textContent=m.mult.toFixed(2)+'x';$('#mineMsg').textContent=`Текущий счёт: ${Math.round(20*m.mult)} pts`}
function mineCashout(){const m=window.mineGame;if(!m?.opened.length)return;const pts=Math.round(20*m.mult);state.points+=pts;record('Mines',true,pts);save();$('#mineMsg').innerHTML=`<span class="success">Зафиксировано +${pts} pts</span>`}
function upgrade(){openModal('Upgrade',`<div class="gameStage"><div class="upgrade"><div class="slot"><div><img src="${gifts[0].img}" style="width:90px;height:90px;object-fit:cover;border-radius:16px"><div>18 pts</div></div></div><div class="arrow">→</div><div class="slot"><div><img src="${gifts[4].img}" style="width:90px;height:90px;object-fit:cover;border-radius:16px"><div>48 pts</div></div></div></div><p class="muted">Выбери рискованный апгрейд: результат определяет мини-игра.</p><button class="primary" onclick="doUpgrade()">Попробовать</button><div id="upResult" class="result"></div></div>`)}
function doUpgrade(){const win=Math.random()<.375;if(win){state.points+=48;state.inventory.unshift(gifts[4])}else state.points=Math.max(0,state.points-18);record('Upgrade',win,win?48:18);$('#upResult').innerHTML=`<span class="${win?'success':'danger'}">${win?'УСПЕХ · получен редкий Gift':'НЕУДАЧА · попытка завершена'}</span>`;save()}
function contract(){openModal('Contracts',`<div class="gameStage"><p class="muted">Выбери 3 коллекционных подарка. Игра создаст новый виртуальный результат из их диапазона.</p><div class="contractItems">${gifts.map((g,i)=>`<div class="card gift" id="cg${i}" onclick="selectContract(${i})"><img src="${g.img}"><b>${g.name}</b><span>${g.value} pts</span></div>`).join('')}</div><button class="primary" onclick="doContract()">Создать контракт</button><div id="conResult" class="result"></div></div>`);window.contractPick=[]}
function selectContract(i){const el=$('#cg'+i);if(window.contractPick.includes(i)){window.contractPick=window.contractPick.filter(x=>x!==i);el.classList.remove('selected')}else if(window.contractPick.length<3){window.contractPick.push(i);el.classList.add('selected')}}
function doContract(){if(window.contractPick.length<3)return toast('Выбери 3 подарка');const total=window.contractPick.reduce((s,i)=>s+gifts[i].value,0),g=gifts[Math.floor(Math.random()*gifts.length)],win=g.value>=total/3;if(win)state.inventory.unshift(g);record('Contract',win,g.value);$('#conResult').innerHTML=`Результат: ${g.name} · ${g.value} pts`;save()}
function duel(){openModal('Duels',`<div class="gameStage"><p class="muted">2–4 игрока соревнуются на колесе. В одиночном режиме второй участник — тренировочный бот.</p><div style="font-size:76px;margin:20px">◉</div><button class="primary" onclick="spinDuel()">Запустить дуэль</button><div id="duelResult" class="result"></div></div>`)}
function spinDuel(){const el=$('#duelResult');let i=0;const t=setInterval(()=>el.textContent=['Игрок 1','Игрок 2','Игрок 3','Игрок 4'][i++%4],80);setTimeout(()=>{clearInterval(t);const win=Math.random()<.5;if(win)state.points+=40;else state.points=Math.max(0,state.points-10);record('Duels',win,win?40:10);el.innerHTML=`<span class="${win?'success':'danger'}">${win?'ТЫ ВЫИГРАЛ · +40 pts':'СОПЕРНИК ВЫИГРАЛ · -10 pts'}</span>`;save()},1800)}
function openRooms(){openModal('Комнаты WebRTC',`<div class="room"><div class="muted">Создай комнату и отправь другу ID. Игроки подключаются напрямую по WebRTC.</div><div class="actions" style="margin:12px 0"><button class="primary" onclick="createRoom()">Создать комнату</button></div><div class="field"><input id="joinId" placeholder="ID комнаты"><button class="secondary" onclick="joinRoom()">Войти</button></div><div id="roomStatus" class="card" style="padding:12px">Нет активной комнаты</div></div>`)}
function createRoom(){peer=new Peer();peer.on('open',id=>{$('#roomStatus').innerHTML=`<b>Комната создана</b><br>ID: <strong>${id}</strong><br><small class="muted">Отправь ID другу</small>`});peer.on('connection',c=>setupConn(c))}
function joinRoom(){const id=$('#joinId').value.trim();if(!id)return toast('Введи ID');peer=new Peer();peer.on('open',()=>setupConn(peer.connect(id)))}
function setupConn(c){conn=c;c.on('open',()=>{toast('Игрок подключён');c.send({type:'hello',name:TG?.initDataUnsafe?.user?.first_name||'Игрок'})});c.on('data',handleNet)}
function handleNet(m){if(m.type==='hello'){$('#roomStatus').innerHTML=`<b>Игрок подключён:</b> ${m.name}<br><button class="primary" onclick="startNetworkBattle()">Запустить Gift Battle</button>`;conn?.send({type:'ack'})}if(m.type==='battle')renderNetworkBattle(m);if(m.type==='pick')toast(`${m.name} открыл раунд`)}
function startNetworkBattle(){conn?.send({type:'battle',round:1});renderNetworkBattle({round:1})}
function renderNetworkBattle(m){openModal('Live Gift Battle',`<div class="gameStage"><div class="badge">ROUND ${m.round}</div><h2>Одновременное открытие</h2><div class="caseSpin">${gifts.slice(0,3).map(g=>`<div class="caseItem"><img src="${g.img}"><div>${g.name}</div></div>`).join('')}</div><button class="primary" onclick="networkPick()">Открыть</button><div id="netResult" class="result"></div></div>`)}
function networkPick(){const g=gifts[Math.floor(Math.random()*gifts.length)],name=TG?.initDataUnsafe?.user?.first_name||'Игрок';conn?.send({type:'pick',name});$('#netResult').textContent=`${g.name} · ${g.value} pts`;toast('Результат отправлен сопернику')}
profile();render();$('#giftGrid').innerHTML=gifts.map(g=>giftHTML(g)).join('');
